@startuml
title Object Diagram - Trạng thái hệ thống sau khi Hủy đơn hàng

object "khachHang : User" as u {
  id = 1005
  email = "binh.jewelry@gmail.com"
}

object "donHang_001 : Order" as o {
  id = 5001
  orderNumber = "ORD-04042026-001"
  orderStatus = CANCELLED
  totalAmount = 5000000
}

object "sp_NhanVang : OrderItem" as item1 {
  id = 8801
  quantity = 1
  price = 5000000
}

object "variant_12 : ProductVariant" as var {
  id = 88
  size = "12"
  stockQuantity = 11 (đã hoàn +1)
}

object "lichSu_1 : OrderStatusHistory" as h1 {
  status = PENDING
  changeTime = "2026-04-04 09:00:00"
}

object "lichSu_2 : OrderStatusHistory" as h2 {
  status = CANCELLED
  changeTime = "2026-04-04 11:30:00"
}

o --> u : user_id = 1005
o *-- item1
item1 --> var : product_variant_id = 88
o *-- h1
o *-- h2

@enduml